name: Android CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  code-style:
    name: Check Kotlin Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run ktlint
        run: |
          chmod +x gradlew
          ./gradlew ktlintCheck